version: "1"

dataset:
  images_folder: "../data/images"
  summary_file: "../data/MPII_DATASET_TRAIN_TEST.csv"
  description:
    image_column: "image"
    train_test_column: "is_training"
    n_joints: 16
    joints:
      column_format: "joint_{JOINTNUMBER}_{IDVISIBILITY}"
      index_format: "id"
      visibility_format: "is_visible"
      names:
        - "00_rAnkle"
        - "01_rKnee"
        - "02_rHip"
        - "03_lHip"
        - "04_lKnee"
        - "05_lAnkle"
        - "06_pelvis"
        - "07_thorax"
        - "08_upperNeck"
        - "09_topHead"
        - "10_rWrist"
        - "11_rElbow"
        - "12_rShoulder"
        - "13_lShoulder"
        - "14_lElbow"
        - "14_lWrist"

data:
  mode: "RGB"
  input_size: 256
  output_size: 64
  shuffle: False
  preprocess:
    area_type: 'full'
    compute_output_coordinates: True
    bbox_factor: 0.5
    heatmap_stddev: 1.5
  normalization:
    images: "MinMax"
    heatmaps: "MinMax"
  augmentation:
    rotation: 45

model:
  name: "TestHourglass"
  stages: 2
  latent_features: 16
  downsamplings: 4
  logs:
    log_folder: '../logs/'
  checkpoints:
    filepath: '../models/'



train:
  intermediate_supervision: True
  validation_ratio: 0.1
  epochs: 5
  epoch_size: 10
  batch_size: 16
  learning_rate:
    value: 0.00001
    decay: False
    decay_step: 2000
    decay_value: 0.99
  optimizer:
    type: "RMSprop"
  loss:
    type: 'binary_crossentropy'
  metrics:
    # - metric:
    #   type: MeanAmountCorrectKeypointsMetric
    #   params:
    #     name: mACKt5
    #     threshold: 5
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
    #   type: MeanAmountCorrectKeypointsMetric
    #   params:
    #     name: mACKt15
    #     threshold: 15
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
    #   type: MeanAmountCorrectKeypointsMetric
    #   params:
    #     name: mACKt25
    #     threshold: 25
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
    #   type: LastAmountCorrectKeypointsMetric
    #   params:
    #     name: lACKt5
    #     threshold: 5
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
    #   type: LastAmountCorrectKeypointsMetric
    #   params:
    #     name: lACKt15
    #     threshold: 15
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
    #   type: LastAmountCorrectKeypointsMetric
    #   params:
    #     name: lACKt25
    #     threshold: 25
    #     stages: 2
    #     size: 64
    #     channels: 16
    # - metric:
      # type: FullAmountCorrectKeypointsMetric
      # params:
        # name: fACKt5
        # threshold: 5
        # stages: 2
        # size: 64
        # channels: 16
    # - metric:
      # type: FullAmountCorrectKeypointsMetric
      # params:
        # name: fACKt15
        # threshold: 15
        # stages: 2
        # size: 64
        # channels: 16
    # - metric:
      # type: FullAmountCorrectKeypointsMetric
      # params:
        # name: fACKt25
        # threshold: 25
        # stages: 2
        # size: 64
        # channels: 16
    - metric:
      type: MeanSquaredError
    - metric:
      type: MeanAbsoluteError
    - metric:
      type: MeanAbsolutePercentageError


